class1groups, class1left = divmod(32,5)
class2groups, class2left = divmod(45,7)
class3groups, class3left = divmod(51,6)
print("Number of students in each group:")
print("Class 1:",class1groups)
print("Class 2:",class2groups)
print("Class 3:",class3groups)
print("")
print("Number of students leftover:")
print("Class 1:",class1left)
print("Class 2:",class2left)
print("Class 3:",class3left)
