print("Enter student's scores: ")
student1 = float(input("Student 1: "))
student2 = float(input("Student 2: "))
student3 = float(input("Student 3: "))
average = ((student1 + student2 + student3) / 3.0)
print("Student's scores: ")
print(student1)
print(student2)
print(student3)
print("Average:",average)